config/routes.rb
Rails.application.routes.draw do
  get 'submission/new'

  root 'pages#index'
  get 'pages/index'

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'pages/ok', as: "ok"
  get 'pages/wrong'
  get 'new_teacher', to: 'pages#new_teacher'
  post 'create_teacher', to: 'pages#create_teacher', as: 'create_teacher'

  get 'profile/:username', to: 'pages#profile', as: "profile"
  
  get 'teacher/show/groups', to: 'teacher#show_groups', as: "teacher_groups_show"
  post 'teacher/show/groups/create', to: 'group#create', as: "teacher_groups_create"
  delete 'teacher/show/groups/:id', to: 'group#destroy', as: "teacher_groups_delete"  

  get 'groups/edit/:id_group', to: 'group#edit', as: "teacher_groups_edit"
  post 'groups/edit', to: 'group#add_student', as: "group_add_student"
  post 'groups/statistics/:id_group', to: 'group#statistics', as: "group_statistics"
  delete 'groups/delete/:id_group/:id_student', to: 'group#delete_student', as: "group_student_delete"

  get 'problem/search', to: 'problem#search', as: "problem_search"
  get 'problem/index', to: 'problem#index', as: "problem_index"
  get 'problem/new', to: 'problem#new', as: "problem_new"
  get 'problem/:id', to: 'problem#show', as: "problem"
  post 'problem/create', to: 'problem#create', as: "problem_create"
  get 'problem/edit/:id', to: 'problem#edit', as: "problem_edit"
  put 'problem/update/:id', to: 'problem#update', as: "problem_update"

  get 'search', to: 'pages#search', as: "search"

  #Modificar primary key, en caso de implementar metodos

  get 'problem/:problem_id/submission/new', to: 'submission#new', as: "submissions_new"
  get 'problem/:problem_id/:username/submission/', to: 'submission#showProblemUser', as: "submissions_problem_user"
  get 'problem/:problem_id/submission/', to: 'submission#showProblem', as: "submissions_problem"
  get ':username/submission/', to: 'submission#showUser', as: "submissions_user"
  post 'problem/:problem_id/submission/create', to: 'submission#create', as: "submissions_create"
  delete 'problem/:problem_id/testcase/delete/:test_idx', to: 'problem#delete_test_case', as: "problem_delete_test_case"
   #Para cuando vayamos a recalificar
   #put 'submission/update/:id', to: 'submission#update', as: "submission_update"

  get 'user/paginate', to: 'user#paginate', as: "user_paginate"
  get 'submission/paginate', to: 'submission#paginate', as: "submission_paginate"
  get 'contest/paginate', to: 'contest#paginate', as: "contest_paginate"
  get 'submission/:submission_id/', to: 'submission#show_details_submission', as: "submission_show"


  get 'problem/:problem_id/testcase/:test_idx', to: 'test_case#show_test_case', as: "problem_show_test_case"
  put 'problem/:problem_id/testcase/update/:test_idx', to: 'test_case#edit', as: "problem_edit_test_case"
  post 'problem/rejudge/:id', to:'problem#rejudge', as: 'problem_rejudge'
  

  get 'contest/index', to: 'contest#index', as: "contest_index"
  get 'contest/new', to: 'contest#new', as: "contest_new"
  get 'contest/my_contests', to: 'contest#my_contests', as: "my_contests"
  get 'contest/:id', to:'contest#show', as: "contest"
  post 'contest', to: 'contest#create', as:'contests'
  get 'contest/edit/:id', to: 'contest#edit', as: "contest_edit"
  patch 'contest/:id', to: 'contest#update', as: "contest_update"
  post 'contest/:contest_id/problem/:problem_id', to: 'contest#add_problem', as: 'contest_add_problem'
  delete 'contest/:contest_id/problem/:problem_index', to: 'contest#delete_problem', as: 'contest_delete_problem'
  put 'contest/:contest_id/problem/:problem_index', to: 'contest#update_problem', as: 'contest_update_problem'
  post 'contest/:contest_id/register/:user_id', to: 'contest#register', as: 'contest_register'
  post 'contest/:contest_id/register/', to: 'contest#register_group', as: 'contest_register_group'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	has_many :groups, dependent: :destroy
	
	validates :username, uniqueness: true, presence: true
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  
  def show_groups
  	teacher_id = Teacher.find_by(username: current_user.username).id
    @teacher = Teacher.find_by(id: teacher_id)
    @user = current_user
  end
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/teacher/show_groups.html.erb
<h3> Tiene los siguientes Grupos: </h3>

<table class = "table table-bordered table-hover">

	<tr>
		<th class="text-center">Nombre</th>
		<th class="text-center">Número de estudiantes</th>
	</tr>

	<% @teacher.groups.each do |group| %>
		<tr>
			<td class="text-center">
				<%= group.name %>
			</td>

			<td class="text-center">
				<%= group.students.count %>

				<div class="pull-right">
					<%= link_to raw("<span class='glyphicon glyphicon-list-alt' aria-hidden='true'></span>"), group_statistics_path(group), class: "btn btn-primary btn-xs", method: :post %>

					<%= link_to raw("<span class='glyphicon glyphicon-edit' aria-hidden='true'></span>"), teacher_groups_edit_path(group), class: "btn btn-success btn-xs" %>

					<%= link_to raw("<span class='glyphicon glyphicon-remove' aria-hidden='true'></span>"), teacher_groups_delete_path(group), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
				</div>
				
			</td>
		</tr>
	<% end %> 
</table>
<div>
<h4>Crear nuevo grupo:</h4>
<%= form_for :group, url: teacher_groups_create_path do |f| %>
	<%= f.label 'Nombre' %>
	<%= f.text_field :name %>
	<% teacher_id = Teacher.find_by(username: current_user.username).id %>
	<%= f.hidden_field :teacher_id, value: teacher_id %>
	<br><br>
	<%= f.submit 'Guardar grupo'%>
<% end %>
</div>