config/routes.rb
Rails.application.routes.draw do
  get 'submission/new'

  root 'pages#index'
  get 'pages/index'

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'pages/ok', as: "ok"
  get 'pages/wrong'
  get 'new_teacher', to: 'pages#new_teacher'
  post 'create_teacher', to: 'pages#create_teacher', as: 'create_teacher'

  get 'profile/:username', to: 'pages#profile', as: "profile"
  
  get 'teacher/show/groups', to: 'teacher#show_groups', as: "teacher_groups_show"
  post 'teacher/show/groups/create', to: 'group#create', as: "teacher_groups_create"
  delete 'teacher/show/groups/:id', to: 'group#destroy', as: "teacher_groups_delete"  

  get 'groups/edit/:id_group', to: 'group#edit', as: "teacher_groups_edit"
  post 'groups/edit', to: 'group#add_student', as: "group_add_student"
  post 'groups/statistics/:id_group', to: 'group#statistics', as: "group_statistics"
  delete 'groups/delete/:id_group/:id_student', to: 'group#delete_student', as: "group_student_delete"

  get 'problem/search', to: 'problem#search', as: "problem_search"
  get 'problem/index', to: 'problem#index', as: "problem_index"
  get 'problem/new', to: 'problem#new', as: "problem_new"
  get 'problem/:id', to: 'problem#show', as: "problem"
  post 'problem/create', to: 'problem#create', as: "problem_create"
  get 'problem/edit/:id', to: 'problem#edit', as: "problem_edit"
  put 'problem/update/:id', to: 'problem#update', as: "problem_update"

  get 'search', to: 'pages#search', as: "search"

  #Modificar primary key, en caso de implementar metodos

  get 'problem/:problem_id/submission/new', to: 'submission#new', as: "submissions_new"
  get 'problem/:problem_id/:username/submission/', to: 'submission#showProblemUser', as: "submissions_problem_user"
  get 'problem/:problem_id/submission/', to: 'submission#showProblem', as: "submissions_problem"
  get ':username/submission/', to: 'submission#showUser', as: "submissions_user"
  post 'problem/:problem_id/submission/create', to: 'submission#create', as: "submissions_create"
  delete 'problem/:problem_id/testcase/delete/:test_idx', to: 'problem#delete_test_case', as: "problem_delete_test_case"
   #Para cuando vayamos a recalificar
   #put 'submission/update/:id', to: 'submission#update', as: "submission_update"

  get 'user/paginate', to: 'user#paginate', as: "user_paginate"
  get 'submission/paginate', to: 'submission#paginate', as: "submission_paginate"
  get 'contest/paginate', to: 'contest#paginate', as: "contest_paginate"
  get 'submission/:submission_id/', to: 'submission#show_details_submission', as: "submission_show"


  get 'problem/:problem_id/testcase/:test_idx', to: 'test_case#show_test_case', as: "problem_show_test_case"
  put 'problem/:problem_id/testcase/update/:test_idx', to: 'test_case#edit', as: "problem_edit_test_case"
  post 'problem/rejudge/:id', to:'problem#rejudge', as: 'problem_rejudge'
  

  get 'contest/index', to: 'contest#index', as: "contest_index"
  get 'contest/new', to: 'contest#new', as: "contest_new"
  get 'contest/my_contests', to: 'contest#my_contests', as: "my_contests"
  get 'contest/:id', to:'contest#show', as: "contest"
  post 'contest', to: 'contest#create', as:'contests'
  get 'contest/edit/:id', to: 'contest#edit', as: "contest_edit"
  patch 'contest/:id', to: 'contest#update', as: "contest_update"
  post 'contest/:contest_id/problem/:problem_id', to: 'contest#add_problem', as: 'contest_add_problem'
  delete 'contest/:contest_id/problem/:problem_index', to: 'contest#delete_problem', as: 'contest_delete_problem'
  put 'contest/:contest_id/problem/:problem_index', to: 'contest#update_problem', as: 'contest_update_problem'
  post 'contest/:contest_id/register/:user_id', to: 'contest#register', as: 'contest_register'
  post 'contest/:contest_id/register/', to: 'contest#register_group', as: 'contest_register_group'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/problem.rb
class Problem < ApplicationRecord
	mount_uploader :url_statement, FileUploader
	validates_processing_of :url_statement
	validates :name, :time_limit, presence: { message: "no puede estar vacio" }
	validates :time_limit, numericality: { message: "debe ser un numero" }
	validates :languages, numericality: { greater_than: 0, message: "debe estar disponible en al menos un lenguaje" }
	has_many :test_cases
    has_many :submissions
    
    has_many :problem_contest_relationships, dependent: :destroy
	has_many :contests, through: :problem_contest_relationships
end

app/controllers/problem_controller.rb
require 'zip'

class ProblemController < ApplicationController
  load_and_authorize_resource except: [:create, :update, :delete_test_case, :rejudge]

  before_action :authenticate_user!, only: [ :create, :edit, :new ]
  before_action :init_pagination, only: [ :index, :search ]

  def index

    maxQuery = 10
    problemStartId = params[:pageIdProblem].to_i*maxQuery

    @problems = Problem.all.offset(problemStartId).limit(maxQuery)
    @problemTotal = Problem.all.count

    if problemStartId+maxQuery >= @problemTotal
      @disableProblemNextButton = " disabled"
    end
    if problemStartId == 0
      @disableProblemPrevButton = " disabled"
    end

  end

  def show
    @problem = Problem.find(params[:id])
    @available_languages = get_list_languages( @problem.languages )
  end
  
  def new
    @problem = Problem.new
  end
  
  def create
    #NOTA: Los @problem.save que se llaman cuando hay errores es para que no reinicie el formulario y muestre que errores hubieron
    @problem = Problem.new
    if params[:problem][:file] != nil and params[:problem][:file].headers.include? ".zip"
      total_pdf = count_pdf_files(params)
      total_test_cases = count_test_cases(params)
      if total_test_cases == 0 or total_pdf != 1 or not create_problem(params)
        @problem.save
        render :new
      else 
        add_test_cases(params)
        redirect_to @problem
      end
    else
      @problem.save
      render :new
    end
  end

  def edit
    @problem = Problem.find(params[:id])
    @available_languages = get_list_languages( @problem.languages )
  end

  def update
    @problem = Problem.find(params[:id])
    @problem.update( {name: params[:problem][:name]})
    @problem.update( {time_limit: params[:problem][:time_limit]})
    @problem.update( {languages: get_languages( params ) })

    if params[:problem][:pdf] != nil and params[:problem][:pdf].headers.include? ".pdf"
      @problem.update( {url_statement: params[:problem][:pdf] })
    end

    if params[:problem][:file] != nil and params[:problem][:file].headers.include? ".zip"
      total_test_cases = count_test_cases(params)
      if total_test_cases > 0
        add_test_cases(params)
      end
    end

    redirect_to @problem
  end

  def delete_test_case
    @record = Problem.find( params[:problem_id] ).test_cases[ params[:test_idx].to_i ]
    @record.destroy
    redirect_to problem_edit_path(params[:problem_id])
  end

  def search  
    maxQuery = 10
    problemStartId = params[:pageIdProblem].to_i*maxQuery

    if( not params.has_key?(:search) )
      @problems = Problem.all.offset(problemStartId).limit(maxQuery).order(params[:order])
      @problemTotal = Problem.all.count
    elsif( is_number?( params[:search] ) )
      @problems = Problem.where("id = ? or lower(name) LIKE ?", Integer("#{params[:search]}"), "%#{params[:search].downcase}%").offset(problemStartId).limit(maxQuery).order(params[:order])
      @problemTotal = Problem.where("id = ? or lower(name) LIKE ?", Integer("#{params[:search]}"), "%#{params[:search].downcase}%").count
    else
      @problems = Problem.where("lower(name) LIKE ?", "%#{params[:search].downcase}%").offset(problemStartId).limit(maxQuery).order(params[:order])
      @problemTotal = Problem.where("lower(name) LIKE ?", "%#{params[:search].downcase}%").count
    end

    if problemStartId+maxQuery >= @problemTotal
      @disableProblemNextButton = " disabled"
    end
    if problemStartId == 0
      @disableProblemPrevButton = " disabled"
    end
  end

  def rejudge
    problem = Problem.find(params[:id])
    judge = JudgeApi.new
    problem.submissions.each do |submission|
      submission.verdict = 'Pending'
      submission.execution_time = '-'
      submission.api_ids = judge.sendSubmission(submission)
      submission.in_queue = false
      submission.save
    end
    redirect_to submissions_problem_path(params[:id])
  end

  private

  def init_pagination
    @disableProblemPrevButton = ""
    @disableProblemNextButton = ""

    @send_order ={
      'id' => "DESC",
      'name' => "DESC",
      'created_at' => "DESC"
    }
    @icon_order ={
      'id' => "",
      'name' => "",
      'created_at' => ""
    }

    if params.has_key?( :order ) and params[:order].split[1].eql?"DESC"
      field = params[:order].split[0]
      @send_order[ field ] = "ASC"
      @icon_order[ field ] = "-alt"
    end
  end

  def create_temporary_file(file)
    filename = file.name
    basename = File.basename(filename)
    tmp = Tempfile.new(basename)
    tmp.binmode
    tmp.write file.get_input_stream.read
    tmp.close
    return tmp.path
  end

  def add_test_cases(params)
    Zip::File.open(params[:problem][:file].tempfile) do |zip_file|
      zip_file.each do |file_1|
        if file_1.name.include? ".in"
          basename_file_1 = File.basename( file_1.name, ".in" )
          zip_file.each do |file_2|
            if file_2.name.include? ".out"
              basename_file_2 = File.basename( file_2.name, ".out" )
              if basename_file_1.eql? basename_file_2
                path_file_1 = create_temporary_file(file_1)
                path_file_2 = create_temporary_file(file_2)
                @problem.test_cases.create(url_input: File.open(path_file_1), url_output: File.open(path_file_2))
              end
            end
          end
        end
      end
    end
  end

  def create_problem(params)
    languages = get_languages(params)
    @problem = Problem.new
    @problem.name = params[:problem][:name]
    @problem.time_limit = params[:problem][:time_limit]
    @problem.languages = languages
    Zip::File.open(params[:problem][:file].tempfile) do |zip_file|
      zip_file.each do |file|
        if file.name.include? ".pdf"
          path_file = create_temporary_file(file)
          @problem.url_statement = File.open(path_file)
          break
        end
      end
    end
    unless @problem.save
      return false
    end
    return true
  end

  def count_pdf_files(params)
    cnt = 0
    Zip::File.open(params[:problem][:file].tempfile) do |zip_file|
      zip_file.each do |file|
        if file.name.include? ".pdf"
          cnt = cnt+1
        end
      end
    end
    return cnt
  end

  def count_test_cases(params) 
    cnt = 0
    Zip::File.open(params[:problem][:file].tempfile) do |zip_file|
      zip_file.each do |file_1|
        if file_1.name.include? ".in"
          basename_file_1 = File.basename( file_1.name, ".in" )
          zip_file.each do |file_2|
            if file_2.name.include? ".out"
              basename_file_2 = File.basename( file_2.name, ".out" )
              if basename_file_1.eql? basename_file_2
                cnt = cnt+1
                break
              end
            end
          end
        end
      end
    end
    return cnt
  end

  def get_languages(params)
    languages = 0
    unless params[:cpp].nil?
      languages |= (1<<0)
    end
    unless params[:java].nil?
      languages |= (1<<1)
    end
    unless params[:py].nil?
      languages |= (1<<2)
    end
    unless params[:c].nil?
      languages |= (1<<3)
    end
    return languages
  end

  def get_list_languages( languages )
    array = []
    array.push([ 'cpp', 'C++', ( languages>>0 )&1 ])
    array.push([ 'java', 'Java', ( languages>>1 )&1 ])
    array.push([ 'py', 'Python', ( languages>>2 )&1 ])
    array.push([ 'c', 'C', ( languages>>3 )&1 ])
    return array
  end 
  
  def problem_params
    params.require(:problem).permit(:name, :time_limit)
  end

  def is_number? string
    true if Integer(string) rescue false
  end
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/views/problem/_table.html.erb
<%if @problems.length == 0%>
	<p>No se encontraron resultados de problemas.</p>
<%else%>
	<% isContestTable = params.has_key?(:contestId) %>
	<% if isContestTable and params[:contestId][0] == '{' %>
		<% params[:contestId] = eval(params[:contestId])[:value] %>
	<% end %>
	<h1>Problemas <span class="badge" ><%=@problemTotal%> </span></h1>
	<div class="table-responsive">
		<!--striped condensed -->
		<table class="table table-bordered table-hoverm table-condensed">
			
			<tr class = "success">
				
				<th>
					ID
					<%new_params = params.merge({controller: "problem", action: "search", order:'id ' + @send_order['id']}).permit!%>
					<%= link_to raw("<span class='pull-right glyphicon glyphicon glyphicon-sort-by-order" + @icon_order['id'] + "' aria-hidden='true'></span>"), new_params, method: 'get',remote: true, class: "no-link" %>
				</th>
				
				<th>
					Nombre
					<%new_params[:order] = 'name ' + @send_order['name']%>
					<%= link_to raw("<span class='pull-right glyphicon glyphicon glyphicon-sort-by-alphabet" + @icon_order['name'] +"' aria-hidden='true'></span>"), new_params, method: 'get',remote: true, class: "no-link" %>
				</th>

				<th>
					Fecha de creación
					<%new_params[:order] = 'created_at ' + @send_order['created_at']%>
					<%= link_to raw("<span class='pull-right glyphicon glyphicon glyphicon-sort-by-order" + @icon_order['created_at'] + "' aria-hidden='true'></span>"), new_params, method: 'get',remote: true, class: "no-link" %>
				</th>

				<%if isContestTable%>
				<th>Agregar</th>
				<%end%>

			</tr>

			<% @problems.each do |problem| %>
			<tr>
				<td> <%= link_to problem.id, problem_path(problem.id) %> </td>
				<td> <%= problem.name %> </td>
				<td> <%= problem.created_at %></td>
				<%if isContestTable%>
				<td>
					<% contest = Contest.find(params[:contestId]) %>
					<%= link_to 'Agregar', contest_add_problem_path({contest_id: contest.id, problem_id: problem.id }), method: 'post', remote: true %>
				</td>
				<%end%>
			</tr>
			<% end %>

		</table>
	</div>

	<div class="text-center">
		<%new_params = params.merge({controller: "problem", action: "search", pageIdProblem: params[:pageIdProblem].to_i-1}).permit!%>
		<%= button_to 'Anterior', new_params, method: 'get', remote: true, class: ("btn btn-default btn-round" + @disableProblemPrevButton) %>
		
		<%new_params[:pageIdProblem] = params[:pageIdProblem].to_i+1%>
		<%= button_to 'Siguiente', new_params , method: 'get', remote: true, class: ("btn btn-default btn-round" + @disableProblemNextButton) %>
	</div>

<%end%>

app/views/problem/edit.html.erb
<div class="form-horizontal dropzone">
  <legend>Editar problema</legend>
  <%= form_for :problem, :method => :PUT, url: problem_update_path do |f| %>
    <div class="form-group" >
      <label class="col-md-4 control-label">ID <%= @problem.id%></label>  
    </div>
    <div class="form-group" >
      <label class="col-md-4 control-label">Nombre</label>  
      <div class="col-md-5">
        <div>
          <%= f.text_field :name, autofocus: true, class: "form-control input-md", placeholder: "name" %>
        </div>
      </div>
    </div>
    <div class="form-group" >
      <label class="col-md-4 control-label">Enunciado del problema</label>  
      <div class="col-md-5">
        <div>
          <%= f.file_field :pdf, class: "form-control input-md", accept: ".pdf", placeholder: "seleccionar archivo..." %>
        </div>
        <p class="help-block"> Este archivo debe ser el enunciado en formato pdf </p> 
      </div>
    </div>
    <div class="form-group" >
      <label class="col-md-4 control-label">Archivo comprimido</label>  
      <div class="col-md-5">
        <div>
          <%= f.file_field :file, class: "form-control input-md", accept: ".zip", placeholder: "seleccionar archivo..." %>
        </div>
        <p class="help-block"> Este archivo debe contener casos de prueba debidamente emparejados con .in y .out</p> 
      </div>
    </div>
    <div class="form-group" >
      <label class="col-md-4 control-label">Tiempo límite</label>  
      <div class="col-md-5">
        <div>
          <%= f.text_field :time_limit, class: "form-control input-md", placeholder: "tiempo en ms" %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-4 control-label">Lenguajes</label>
      <div class="col-md-5">
        <% @available_languages.each do |lang| -%>
          <% val = "0" %>
          <% if lang[ 2 ] == 1 %>
            <% val = "1" %>
          <% end %> 
          <%= check_box_tag(lang[ 0 ], value = val, checked = ( val == "1" )) %>
          <%= label_tag(lang[ 0 ], lang[ 1 ]) %>
        <% end %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-md-4 control-label"></label>
      <div class="col-md-4">
        <%= f.submit "Editar problema", class: "btn btn-primary", data: {disable_with: "Editando..."} %>
      </div>
    </div>
  <% end %>
</div>

<br>
<legend>Casos de prueba</legend>
<div class="table-responsive">
  
  <table class="table table-bordered table-hover">
    
    <%caseCnt = 0%>
    <%@problem.test_cases.each do |tCase|%>

      <tr>

        <td class="text-center">
          Test Case <%=(caseCnt + 1)%>

          <div class="pull-right">
            <%= link_to raw("<span class='glyphicon glyphicon-edit' aria-hidden='true'></span>"), problem_show_test_case_path( @problem.id, caseCnt ), class: "btn btn-success btn-xs" %>

            <%= link_to raw("<span class='glyphicon glyphicon-remove' aria-hidden='true'></span>"), problem_delete_test_case_path( @problem.id, caseCnt ), class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>

        </td>

        <%caseCnt += 1%>

      </tr>

    <%end%>

  </table>

</div>

app/views/problem/index.html.erb
<div id = "problems_table">
	<%= render "table" %>
</div>

app/views/problem/new.html.erb
<div class="form-horizontal dropzone">
  <legend>Nuevo problema</legend>
  <%= form_for :problem, url: problem_create_path do |f| %>
    <% error = check_error(@problem.errors, :name) %>
    <div class="form-group <%= error[:error_class] %>" >
      <label class="col-md-4 control-label">Nombre</label>  
      <div class="col-md-5">
        <div>
          <%= f.text_field :name, autofocus: true, class: "form-control input-md", placeholder: "nombre" %>
        </div>
        <p class="help-block"> <%= error[:error_message] %></p> 
      </div>
    </div>
    <% error = check_error(@problem.errors, :file) %>
    <div class="form-group <%= error[:error_class] %>" >
      <label class="col-md-4 control-label">Archivo comprimido</label>  
      <div class="col-md-5">
        <div>
          <%= f.file_field :file, class: "form-control input-md", accept: ".zip", placeholder: "seleccionar archivo..." %>
        </div>
        <p class="help-block"> Este archivo debe contener el enunciado en formato pdf y los casos de prueba debidamente emparejados con .in y .out</p> 
      </div>
    </div>
    <% error = check_error(@problem.errors, :time_limit) %>
    <div class="form-group <%= error[:error_class] %>" >
      <label class="col-md-4 control-label">Tiempo límite</label>  
      <div class="col-md-5">
        <div>
          <%= f.text_field :time_limit, class: "form-control input-md", placeholder: "tiempo en ms" %>
        </div>
        <p class="help-block"> <%= error[:error_message] %></p> 
      </div>
    </div>
    <% error = check_error(@problem.errors, :languages) %>
    <div class="form-group <%= error[:error_class] %>">
      <label class="col-md-4 control-label">Lenguajes</label>
      <div class="col-md-5">
        <%= check_box_tag(:c) %>
        <%= label_tag(:c, "C") %>
        <%= check_box_tag(:cpp) %>
        <%= label_tag(:cpp, "C++") %>
        <%= check_box_tag(:java) %>
        <%= label_tag(:java, "Java") %>
        <%= check_box_tag(:py) %>
        <%= label_tag(:py, "Python") %>
        <p class="help-block"> <%= error[:error_message] %></p> 
      </div>
    </div>

    <div class="form-group">
      <label class="col-md-4 control-label"></label>
      <div class="col-md-4">
        <%= f.submit "Subir problema", class: "btn btn-primary", data: {disable_with: "Creando..."}%>
      </div>
    </div>
  <% end %>
</div>

app/views/problem/search.js.erb
$('#problems_table').html('<%= j render "table" %>');

app/views/problem/show.html.erb
<div class="form-horizontal">
  <legend>
    <p class = "problem_title"><%= @problem.id %>. <%= @problem.name %></p>
    <p class = "problem_info">
      Time Limit: <%= @problem.time_limit %> ms
    </p>
    <p class = "problem_info"> 
      <% @available_languages.each do |lang| -%>
        <% if lang[ 2 ] == 1 %>
          <%= lang[ 1 ] %>
        <% end %>
      <% end %>
    </p>
  </legend>
    <%= link_to '<button class="fa fa-upload btn-oldstyle">   Submit</button>'.html_safe, submissions_new_path(@problem.id) %>
    <%= link_to '<button class="fa fa-bar-chart btn-oldstyle-2">   Submissions Problem</button>'.html_safe, submissions_problem_path(@problem.id) %>
    <%if current_user != nil%>
      <%= link_to '<button class="fa fa-bar-chart btn-oldstyle-2">   My Submissions</button>'.html_safe, submissions_problem_user_path(@problem.id, current_user.username) %>
    <%end%>
    <%= link_to '<button class="fa fa-pencil-square-o btn-oldstyle-3 pull-right">   Edit Problem</button>'.html_safe, problem_edit_path(@problem.id) %>
  <iframe src="http://docs.google.com/viewer?url=<%= u @problem.url_statement.url %>&embedded=true" class = "problem_statement responsive" style="border: none;"></iframe>
</div>