config/routes.rb
Rails.application.routes.draw do
  get 'submission/new'

  root 'pages#index'
  get 'pages/index'

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'pages/ok', as: "ok"
  get 'pages/wrong'
  get 'new_teacher', to: 'pages#new_teacher'
  post 'create_teacher', to: 'pages#create_teacher', as: 'create_teacher'

  get 'profile/:username', to: 'pages#profile', as: "profile"
  
  get 'teacher/show/groups', to: 'teacher#show_groups', as: "teacher_groups_show"
  post 'teacher/show/groups/create', to: 'group#create', as: "teacher_groups_create"
  delete 'teacher/show/groups/:id', to: 'group#destroy', as: "teacher_groups_delete"  

  get 'groups/edit/:id_group', to: 'group#edit', as: "teacher_groups_edit"
  post 'groups/edit', to: 'group#add_student', as: "group_add_student"
  post 'groups/statistics/:id_group', to: 'group#statistics', as: "group_statistics"
  delete 'groups/delete/:id_group/:id_student', to: 'group#delete_student', as: "group_student_delete"

  get 'problem/search', to: 'problem#search', as: "problem_search"
  get 'problem/index', to: 'problem#index', as: "problem_index"
  get 'problem/new', to: 'problem#new', as: "problem_new"
  get 'problem/:id', to: 'problem#show', as: "problem"
  post 'problem/create', to: 'problem#create', as: "problem_create"
  get 'problem/edit/:id', to: 'problem#edit', as: "problem_edit"
  put 'problem/update/:id', to: 'problem#update', as: "problem_update"

  get 'search', to: 'pages#search', as: "search"

  #Modificar primary key, en caso de implementar metodos

  get 'problem/:problem_id/submission/new', to: 'submission#new', as: "submissions_new"
  get 'problem/:problem_id/:username/submission/', to: 'submission#showProblemUser', as: "submissions_problem_user"
  get 'problem/:problem_id/submission/', to: 'submission#showProblem', as: "submissions_problem"
  get ':username/submission/', to: 'submission#showUser', as: "submissions_user"
  post 'problem/:problem_id/submission/create', to: 'submission#create', as: "submissions_create"
  delete 'problem/:problem_id/testcase/delete/:test_idx', to: 'problem#delete_test_case', as: "problem_delete_test_case"
   #Para cuando vayamos a recalificar
   #put 'submission/update/:id', to: 'submission#update', as: "submission_update"

  get 'user/paginate', to: 'user#paginate', as: "user_paginate"
  get 'submission/paginate', to: 'submission#paginate', as: "submission_paginate"
  get 'contest/paginate', to: 'contest#paginate', as: "contest_paginate"
  get 'submission/:submission_id/', to: 'submission#show_details_submission', as: "submission_show"


  get 'problem/:problem_id/testcase/:test_idx', to: 'test_case#show_test_case', as: "problem_show_test_case"
  put 'problem/:problem_id/testcase/update/:test_idx', to: 'test_case#edit', as: "problem_edit_test_case"
  post 'problem/rejudge/:id', to:'problem#rejudge', as: 'problem_rejudge'
  

  get 'contest/index', to: 'contest#index', as: "contest_index"
  get 'contest/new', to: 'contest#new', as: "contest_new"
  get 'contest/my_contests', to: 'contest#my_contests', as: "my_contests"
  get 'contest/:id', to:'contest#show', as: "contest"
  post 'contest', to: 'contest#create', as:'contests'
  get 'contest/edit/:id', to: 'contest#edit', as: "contest_edit"
  patch 'contest/:id', to: 'contest#update', as: "contest_update"
  post 'contest/:contest_id/problem/:problem_id', to: 'contest#add_problem', as: 'contest_add_problem'
  delete 'contest/:contest_id/problem/:problem_index', to: 'contest#delete_problem', as: 'contest_delete_problem'
  put 'contest/:contest_id/problem/:problem_index', to: 'contest#update_problem', as: 'contest_update_problem'
  post 'contest/:contest_id/register/:user_id', to: 'contest#register', as: 'contest_register'
  post 'contest/:contest_id/register/', to: 'contest#register_group', as: 'contest_register_group'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contest.rb
class Contest < ApplicationRecord
	belongs_to :teacher
	
	attr_accessor :contest_running

	validates :name, :start_date, :end_date, presence: { message: "es obligatorio" }
	validate :dates_are_correct
	validate :valid_initial_date, unless: :contest_running

	has_many :problem_contest_relationships, dependent: :destroy
	has_many :problems, through: :problem_contest_relationships

	has_many :user_contest_relationships, dependent: :destroy
	has_many :users, through: :user_contest_relationships

	def dates_are_correct
		# Esto es para evita que una persona temine un contest en tiempo anterior al actual
		# pero posterior al start_date
		cur_time = Time.new + 5*60
	    if start_date < end_date == false
	      errors.add(:start_date, 'debe ser antes de la fecha final')
	    elsif cur_time < end_date == false
	      errors.add(:end_date, 'El contest no puede terminar tan pronto')
	    end
  	end

  	def valid_initial_date
		#Esto es para que el contest empiece minimo 5 minutos despues de la fecha actual
		cur_time = Time.new + 5*60
	    if cur_time < start_date == false 
	      errors.add(:start_date, 'debe ser al menos 5 minutos despues de la fecha actual')
	    end

  	end

end

app/controllers/contest_controller.rb
class ContestController < ApplicationController
	load_and_authorize_resource except: [:create, :register, :update, :add_problem, :delete_problem, :update_problem]

	before_action :authenticate_user!, except: [ :show, :index ]
	before_action :init_pagination, only: [ :index, :paginate, :my_contests ]
	helper_method :calculate_score, :count_submissions, :count_accepted

	def index

		maxQuery = 10
		@cur_date = Time.new
		@past_contest = Contest.where("end_date < ? ", @cur_date).limit(maxQuery)
		@past_contest_total = Contest.where("end_date < ? ", @cur_date).count
		@comming_contest = Contest.where("start_date > ? ", @cur_date).limit(maxQuery)
		@comming_contest_total = Contest.where("start_date > ? ", @cur_date).count
		@running_contest = Contest.where("start_date <= ? AND end_date >= ? ", @cur_date, @cur_date).limit(maxQuery)
		@running_contest_total = Contest.where("start_date <= ? AND end_date >= ? ", @cur_date, @cur_date).count

		@disablePrevButton = { 'Past' => ' disabled',
								'Comming' => ' disabled',
								'Running' => ' disabled' }

		if @past_contest_total <= maxQuery
			@disableNextButton['Past'] = " disabled"
		end
		if @comming_contest_total <= maxQuery
			@disableNextButton['Comming'] = " disabled"
		end
		if @running_contest_total <= maxQuery
			@disableNextButton['Running'] = " disabled"
		end

	end

	def paginate
		maxQuery = 10
		contestStartId = params['pageId' + params[:type]].to_i*maxQuery

		cur_date = params[:cur_date].to_datetime
		if( params[:type].eql?('Past') )
			@contests = Contest.where("end_date < ? ", cur_date).offset(contestStartId).limit(maxQuery).order(params[:order])
			@contests_total = Contest.where("end_date < ? ", cur_date).count
		elsif( params[:type].eql?('Comming') )
			@contests = Contest.where("start_date > ? ", cur_date).offset(contestStartId).limit(maxQuery).order(params[:order])
			@contests_total = Contest.where("start_date > ? ", cur_date).count
		else
			@contests = Contest.where("start_date <= ? AND end_date >= ? ", cur_date, cur_date).offset(contestStartId).limit(maxQuery).order(params[:order])
			@contests_total = Contest.where("start_date <= ? AND end_date >= ? ", cur_date, cur_date).count
		end

		if contestStartId+maxQuery >= @contests_total
			@disableNextButton[ params[:type] ] = " disabled"
		end
		if contestStartId == 0
			@disablePrevButton[ params[:type] ] = " disabled"
		end
	end

	def show
		@contest = Contest.find(params[:id])
		@problemsIn = @contest.problem_contest_relationships
		@registeredUsers = @contest.users
		# esto ordena en orden ascendente primero por el score total, y luego por la cantidad de problemas
		# entre mas score mejor, entre menos problemas mejor y luego por la cantidad de envios.
		@registeredUsers = @registeredUsers.sort_by{ |p| [-calculate_score(p.id), count_ac_problems(p.id), count_total_submissions(p.id)] }
		if current_user != nil and @contest.teacher_id == current_user.id
			@teacher_groups = Teacher.find(current_user.id).groups
		end
	end

	def register 
		UserContestRelationship.create(register_params)
		redirect_to contest_path(params[:contest_id])
	end

	def register_group
		@group_students = Group.find(params[:group_id]).students
		if GroupAndContest.find_by(contest_id: params[:contest_id], group_id: params[:group_id]) == nil
			GroupAndContest.create(contest_id: params[:contest_id], group_id: params[:group_id])
		end
		@group_students.each do |g|
		    UserContestRelationship.create(contest_id: params[:contest_id], user_id: User.find_by(username: g.username).id)
		end
		redirect_to contest_path(params[:contest_id])
	end

	def new
		@teacher_id = Teacher.find_by(username: current_user.username).id
		@contest = Contest.new
		@contest.start_date = Time.new + 6*60
		@contest.end_date = Time.new + 6*60
	end

	def create
		@contest = Contest.new(contest_params)
		if @contest.save
    		redirect_to contest_index_path
    	else
    		@teacher_id = Teacher.find_by(username: current_user.username).id
    		@contest.start_date = Time.new + 6*60
    		render :new
    	end
	end
	
	def edit
		@contest = Contest.find(params[:id])
		@teacher_id = Teacher.find_by(username: current_user.username).id
		@problemsIn = @contest.problem_contest_relationships
	end

	def update
		@contest = Contest.find(params[:id])
		# Si se pudo modificar la fecha, es porque no estaba bloqueada, y por ende, hay que ejecutar
		# la validacion, se asume que ya la fecha que estaba es valida porque estamos en un update
		# esta variable se salta la validacion de la fecha inicial cuando el contest 
		# haya empezado
		@contest.contest_running = params[:contest][:"start_date(1i)"] == nil

		tmp_date = @contest.start_date
		@contest.attributes = contest_params		

	    if @contest.save
    		redirect_to contest_path(@contest.id)	
	    else
	    	@contest.start_date = tmp_date
	    	render :edit
	    end
	end

	def add_problem
		@contest = Contest.find(params[:contest_id])
		@problemsIn = @contest.problem_contest_relationships
		ProblemContestRelationship.create(contest_id: params[:contest_id], problem_id: params[:problem_id], score: 1)
	end

	def delete_problem
		@contest = Contest.find(params[:contest_id])
		@problemsIn = @contest.problem_contest_relationships
		ProblemContestRelationship.delete(params[:problem_index])
	end

	def update_problem
		@contest = Contest.find(params[:contest_id])
		@problemsIn = @contest.problem_contest_relationships
		record = ProblemContestRelationship.find(params[:problem_index])
		if !record.update(score: params[:score])
			render :edit
		end
	end

	def my_contests

		maxQuery = 10
		@cur_date = Time.new

		teacher_id = Teacher.find_by(username: current_user.username).id

		@past_contest = Contest.where("end_date < ? AND teacher_id = ?", @cur_date, teacher_id).limit(maxQuery)
		@past_contest_total = Contest.where("end_date < ? AND teacher_id = ?", @cur_date, teacher_id).count
		@comming_contest = Contest.where("start_date > ? AND teacher_id = ?", @cur_date, teacher_id).limit(maxQuery)
		@comming_contest_total = Contest.where("start_date > ? AND teacher_id = ?", @cur_date, teacher_id).count
		@running_contest = Contest.where("start_date <= ? AND end_date >= ? AND teacher_id = ?", @cur_date, @cur_date, teacher_id).limit(maxQuery)
		@running_contest_total = Contest.where("start_date <= ? AND end_date >= ? AND teacher_id = ?", @cur_date, @cur_date, teacher_id).count

		@disablePrevButton = { 'Past' => ' disabled',
								'Comming' => ' disabled',
								'Running' => ' disabled' }

		if @past_contest_total <= maxQuery
			@disableNextButton['Past'] = " disabled"
		end
		if @comming_contest_total <= maxQuery
			@disableNextButton['Comming'] = " disabled"
		end
		if @running_contest_total <= maxQuery
			@disableNextButton['Running'] = " disabled"
		end

	end

	private

	def init_pagination
		types = ['Past', 'Running', 'Comming']

		@disablePrevButton ||= {}
		@disableNextButton ||= {}
		@send_order ||= {}
		@icon_order ||= {}
		types.each do |type|
			@disablePrevButton[ type ] = ''
			@disableNextButton[ type ] = ''
			@send_order[ type ] = {
				'id' => 'DESC',
				'name' => 'DESC',
				'start_date' => 'DESC',
				'end_date' => 'DESC'
			}
			@icon_order[ type ] = {
				'id' => '',
				'name' => '',
				'start_date' => '',
				'end_date' => ''
			}
		end

		if params.has_key?( :order ) and params[:order].split[1].eql?"DESC"
			field = params[:order].split[0]
			@send_order[params[:type]][ field ] = "ASC"
			@icon_order[params[:type]][ field ] = "-alt"
		end
	end

 	def contest_params
    	params.require(:contest).permit(:name, :teacher_id, :start_date, :end_date)
  	end
  	def register_params
    	params.permit(:contest_id, :user_id)
  	end

  	# Return the maximum number of test cases passed by a submission made in a contest by an user
  	def count_accepted(user_id, problem_id)
  		submissionsInContest = Submission.where("user_id = ? AND problem_id = ? AND created_at > ? AND created_at < ?", user_id, problem_id, @contest.start_date, @contest.end_date)
  		count = 0
  		# The method to_i in ruby parse to integer every number from the start of the string
  		# If there isn't any, return 0
  		submissionsInContest.each do |s|
  			count = [count, s.verdict.to_i ].max
  		end
  		return count
  	end

  	def count_ac_problems(user_id)
  		count = 0
  		@problemsIn.each do |r|
  			if count_accepted(user_id, r.problem.id) == r.problem.test_cases.count
  				count = count + 1
  			end
  		end
  		return count
  	end

  	def count_total_submissions(user_id)
  		count = 0
  		@problemsIn.each do |r|
  			count = count + count_submissions(user_id, r.problem.id)
  		end
  		return count
  	end

  	def calculate_score(user_id)
  		count = 0
  		@problemsIn.each do |r|
  			tmp = count_accepted(user_id, r.problem.id)
  			count = count + r.score * tmp
  		end
  		return count
  	end

  	# Return the number of submissions made for a user in a contest
  	def count_submissions(user_id, problem_id)
  		Submission.where("user_id = ? AND problem_id = ? AND created_at > ? AND created_at < ? ", user_id, problem_id, @contest.start_date, @contest.end_date).count
  	end
end

app/helpers/contest_helper.rb
module ContestHelper
end

app/views/contest/_form.html.erb
<%
    Struct.new("Error", :error_class, :error_message)

    def check_error(errors, param)
        if errors.include?(param)
            return Struct::Error.new(" has-error", "*"+errors.full_messages_for(param)[0])
        else 
            return Struct::Error.new( "", "" )
        end
    end
%>

<div class="form-horizontal dropzone">
  <legend><%= title %> Competencia</legend>
  <%= form_for (@contest) do |f| %>
    <% error = check_error(@contest.errors, :name) %>
    <div class="form-group <%= error[:error_class] %>" >
      <label class="col-md-4 control-label">Nombre</label>  
      <div class="col-md-5">
        <div>
          <%= f.text_field :name, autofocus: true, class: "form-control input-md", placeholder: "nombre" %>
        </div>
        <p class="help-block"> <%= error[:error_message] %></p> 
      </div>
    </div>
    <% error = check_error(@contest.errors, :start_date) %>
    <div class="form-group <%= error[:error_class] %>" >
      <label class="col-md-4 control-label">Fecha de inicio</label>  
      <div class="col-md-5">
        <div>
          <% 
            cur_time = Time.new;
            if @contest.start_date != nil and @contest.start_date < cur_time
          %>
              <%= f.datetime_select :start_date, :disabled => true, class: "form-control input-md"%>
          <%else%>
              <%= f.datetime_select :start_date, class: "form-control input-md"%>
          <%end%>

        </div>
        <p class="help-block"> <%= error[:error_message] %></p> 
      </div>
    </div>
    <% error = check_error(@contest.errors, :end_date) %>
    <div class="form-group <%= error[:error_class] %>" >
      <label class="col-md-4 control-label">Fecha de finalización</label>  
      <div class="col-md-5">
        <div>
          <%= f.datetime_select :end_date, class: "form-control input-md"%>
        </div>
        <p class="help-block"> <%= error[:error_message] %></p> 
      </div>
    </div>
    <%= f.hidden_field :teacher_id, value: @teacher_id%>

    <div class="form-group">
      <label class="col-md-4 control-label"></label>
      <div class="col-md-4">
        <%= f.submit button_text, class: "btn btn-primary", data: {disable_with: "Creando..."}%>
      </div>
    </div>
  <% end %>
</div>

app/views/contest/_table_contest_index.html.erb
<% type ||= params[:type] %>
<% params[:cur_date] ||= @cur_date%>
<h1><%=type + " Contests"%> <span class="badge" ><%=total_contests%> </span></h1>
<div class="table-responsive">
	<!--striped condensed -->
	<table class="table table-bordered table-hoverm table-condensed">
		
		<%if total_contests > 0 %>
		<tr class = "success">
			
			<th>
				ID
				<%new_params = params.merge({action: "paginate", type: type, order:'id ' + @send_order[type]['id']}).permit!%>
				<%= link_to raw("<span class='pull-right glyphicon glyphicon glyphicon-sort-by-order" + @icon_order[type]['id'] + "' aria-hidden='true'></span>"), new_params, method: 'get',remote: true, class: "no-link" %>
			</th>
			
			<th>
				Nombre
				<%new_params[:order] = 'name ' + @send_order[type]['name']%>
				<%= link_to raw("<span class='pull-right glyphicon glyphicon glyphicon-sort-by-alphabet" + @icon_order[type]['name'] +"' aria-hidden='true'></span>"), new_params, method: 'get',remote: true, class: "no-link" %>
			</th>

			<th>
				Fecha de Inicio
				<%new_params[:order] = 'start_date ' + @send_order[type]['start_date']%>
				<%= link_to raw("<span class='pull-right glyphicon glyphicon glyphicon-sort-by-attributes" + @icon_order[type]['start_date'] + "' aria-hidden='true'></span>"), new_params, method: 'get',remote: true, class: "no-link" %>
			</th>

			<th>
				Fecha de Terminación
				<%new_params[:order] = 'end_date ' + @send_order[type]['end_date']%>
				<%= link_to raw("<span class='pull-right glyphicon glyphicon glyphicon-sort-by-attributes" + @icon_order[type]['end_date'] + "' aria-hidden='true'></span>"), new_params, method: 'get',remote: true, class: "no-link" %>
			</th>

		</tr>
		<%end%>

		<% contests.each do |contest| %>
		<tr>
			<td> <%= link_to contest.id, contest_path(contest.id) %> </td>
			<td> <%= contest.name %> </td>
			<td> <%= contest.start_date %></td>
			<td> <%= contest.end_date %></td>
		</tr>
		<% end %>

	</table>
</div>

<%if total_contests > 0 %>
<div class="text-center">
	<%new_params = params.merge({action: "paginate", type: type, 'pageId' + type => params['pageId' + type].to_i-1}).permit!%>
	<%= button_to 'Anterior', new_params, method: 'get', remote: true, class: ("btn btn-default btn-round"  + @disablePrevButton[type])%>
	
	<%new_params['pageId' + type] = params['pageId' + type].to_i+1%>
	<%= button_to 'Siguiente', new_params , method: 'get', remote: true, class: ("btn btn-default btn-round" + @disableNextButton[type]) %>
</div>
<%end%>

app/views/contest/_table_problems_in_contest.html.erb
<!--Antes estaba length  == 0 -->
<%if @problemsIn == nil%>
	<p>No hay problemas agregados al contest.</p>
<%else%>
	<h1>Problemas actuales <span class="badge" ><%=@problemsIn.length%> </span></h1>
	<div class="table-responsive">
		<!--striped condensed -->
		<table id="problemsInContestTable" class="table table-bordered table-hoverm table-condensed">
			<tr class = "success">
				<th>
					ID
				</th>
				
				<th>
					Nombre
					
				</th>
				<th id="problemTh3">Puntuación</th>
				<th id="problemTh4">Eliminar</th>
				<th id="problemTh4">Rejuzgar</th>
			</tr>
			<% @problemsIn.each do |r| %>
			<tr>
				<td> <%= link_to r.problem.id, problem_path(r.problem.id) %> </td>
				<td> <%= r.problem.name %> </td>
				<td>
					<%= text_field_tag 'score'+r.id.to_s , r.score %>
					<% call_function = "update_link_problem_score('#{r.id}')" %>
					<%= link_to 'Actualizar', contest_update_problem_path({contest_id: @contest.id, problem_index: r.id, score: 2}), method: 'put', remote: true, onclick: call_function, id: 'link_update' + r.id.to_s %>
				</td>
				<td> <%= link_to 'Eliminar', contest_delete_problem_path({contest_id: @contest.id, problem_index: r.id }), method: 'delete', remote: true %></td>
				<td> <%= link_to 'Rejuzgar', problem_rejudge_path(r.problem.id), method: 'post' %> </td>
			</tr>

			<% end %>
		</table>
	</div>

<%end%>

<script type="text/javascript">
	function update_link_problem_score(id){
		var link = document.getElementById('link_update' + id);
		var newScore = document.getElementById('score'+id).value;
		var newLink = link.href.substr(0, link.href.indexOf('=')+1);
		link.href = newLink.concat(newScore);
		link.innerHTML = "actualizando";
	}
</script>

app/views/contest/add_problem.js.erb
$('#current_problems').html('<%= j render "table_problems_in_contest" %>');

app/views/contest/delete_problem.js.erb
$('#current_problems').html('<%= j render "table_problems_in_contest" %>');

app/views/contest/edit.html.erb
<%= render "form", title:'Editar', button_text: 'Guardar' %>
<div id="current_problems">
  <%= render "table_problems_in_contest" %> 
</div>
<div>
  <h1> Agregar problemas </h1>
	<%= form_tag problem_search_path, method: 'get', remote: true do %>
    <div class="input-group custom-search-form">
      <%= text_field_tag :search, "", placeholder: 'Buscar...', class: 'form-control' %>
      <%= hidden_field_tag :contestId, value: @contest.id %>
      <span class="input-group-btn">
        <%= button_tag(type: "submit", class: "btn btn-default") do %>
            <i class="fa fa-search"></i>
        <% end %>
      </span>
    <% end %>
    </div>
</div>	
<div id= "problems_table"></div>

app/views/contest/index.html.erb
<div id="RunningTable">
	<%= render "table_contest_index", contests: @running_contest, total_contests: @running_contest_total, type: "Running" %>
</div>
<br>

<div id="CommingTable">
	<%= render "table_contest_index", contests: @comming_contest, total_contests: @comming_contest_total, type: "Comming" %>
</div>
<br>

<div id="PastTable">
	<%= render "table_contest_index", contests: @past_contest, total_contests: @past_contest_total, type: "Past" %>
</div>

app/views/contest/my_contests.html.erb
<div id="RunningTable">
	<%= render "table_contest_index", contests: @running_contest, total_contests: @running_contest_total, type: "Running" %>
</div>
<br>

<div id="CommingTable">
	<%= render "table_contest_index", contests: @comming_contest, total_contests: @comming_contest_total, type: "Comming" %>
</div>
<br>

<div id="PastTable">
	<%= render "table_contest_index", contests: @past_contest, total_contests: @past_contest_total, type: "Past" %>
</div>

app/views/contest/new.html.erb
<%= render "form", title: 'Nueva', button_text: 'Crear' %>

app/views/contest/paginate.js.erb
$( '#' + '<%=params[:type]%>' + 'Table' ).html( '<%= j render "table_contest_index", contests: @contests, total_contests: @contests_total %>' );

app/views/contest/show.html.erb
<div id="contestInfo">
	<center>
		<h1> <%= @contest.name %> </h1>
	</center>
	Fecha de inicio: <%= @contest.start_date %>
	<br>
	Fecha de finalización: <%= @contest.end_date %>
	<% if user_signed_in? %>
		<% if Time.new < @contest.end_date and @registeredUsers.include?(current_user) == false %>
			<%= button_to 'Registrar', contest_register_path(contest_id: @contest.id, user_id: current_user.id), method: 'post', class: "btn btn-default btn-round" %>
		<% end %>
		<% tmp_teacher = Teacher.find_by(username: current_user.username) %>
		<% if tmp_teacher != nil and tmp_teacher.id == @contest.teacher_id %>
			<%= button_to 'Editar', contest_edit_path(@contest.id), method: 'get', class: "btn btn-default btn-round" %>
		<% end %>

		<% if @teacher_groups != nil and @teacher_groups.count != 0%>
			<%= form_tag contest_register_group_path(@contest.id), method: 'post' do %>
			  <div class="" >
			      <label class=" control-label">Registrar Grupo</label>  
			      <div class="">
			        <div>
			          <%= select_tag 'group_id', options_for_select(@teacher_groups.collect{ |u| [u.name, u.id] }) %>
			          <%= button_tag(type: "submit", class: "btn btn-default") do %>
			            <i class="fa fa-sign-in"> Registrar</i>
			        <% end %>
			        </div>
			      </div>
			    </div>

			    
			<% end %>
		<% end %>

	<% end %>

	
	<br>
	<br>
</div>

<div class="table-responsive">
	<!--striped condensed -->
	<table id="scoreboard" class="table table-bordered table-hoverm table-condensed">
		<tr class = "success">
			<th>#</th>
			<th>Correo</th>
			<th>Puntuación</th>
			<% @problemsIn.each do |r| %>
				<th> <%= link_to r.problem.id, problem_path(r.problem.id) %> </th>
			<% end %>
		</tr>
		<% number = 0 %>
		<% @registeredUsers.each do |user| %>
			<tr>
				<td> <%= number = number + 1 %> </td>
				<td> <%= user.email %> </td>
				<td> <%= calculate_score(user.id) %></td>
				<% @problemsIn.each do |r| %>
					<td> <%= count_accepted(user.id, r.problem.id) * r.score %> / <%= r.problem.test_cases.count * r.score %></td>
			<% end %>
		<% end %>
	</table>
</div>

app/views/contest/update_problem.js.erb
$('#current_problems').html('<%= j render "table_problems_in_contest" %>');