config/routes.rb
Rails.application.routes.draw do
  get 'submission/new'

  root 'pages#index'
  get 'pages/index'

  devise_for :users, :controllers => { registrations: 'registrations' }

  get 'pages/ok', as: "ok"
  get 'pages/wrong'
  get 'new_teacher', to: 'pages#new_teacher'
  post 'create_teacher', to: 'pages#create_teacher', as: 'create_teacher'

  get 'profile/:username', to: 'pages#profile', as: "profile"
  
  get 'teacher/show/groups', to: 'teacher#show_groups', as: "teacher_groups_show"
  post 'teacher/show/groups/create', to: 'group#create', as: "teacher_groups_create"
  delete 'teacher/show/groups/:id', to: 'group#destroy', as: "teacher_groups_delete"  

  get 'groups/edit/:id_group', to: 'group#edit', as: "teacher_groups_edit"
  post 'groups/edit', to: 'group#add_student', as: "group_add_student"
  post 'groups/statistics/:id_group', to: 'group#statistics', as: "group_statistics"
  delete 'groups/delete/:id_group/:id_student', to: 'group#delete_student', as: "group_student_delete"

  get 'problem/search', to: 'problem#search', as: "problem_search"
  get 'problem/index', to: 'problem#index', as: "problem_index"
  get 'problem/new', to: 'problem#new', as: "problem_new"
  get 'problem/:id', to: 'problem#show', as: "problem"
  post 'problem/create', to: 'problem#create', as: "problem_create"
  get 'problem/edit/:id', to: 'problem#edit', as: "problem_edit"
  put 'problem/update/:id', to: 'problem#update', as: "problem_update"

  get 'search', to: 'pages#search', as: "search"

  #Modificar primary key, en caso de implementar metodos

  get 'problem/:problem_id/submission/new', to: 'submission#new', as: "submissions_new"
  get 'problem/:problem_id/:username/submission/', to: 'submission#showProblemUser', as: "submissions_problem_user"
  get 'problem/:problem_id/submission/', to: 'submission#showProblem', as: "submissions_problem"
  get ':username/submission/', to: 'submission#showUser', as: "submissions_user"
  post 'problem/:problem_id/submission/create', to: 'submission#create', as: "submissions_create"
  delete 'problem/:problem_id/testcase/delete/:test_idx', to: 'problem#delete_test_case', as: "problem_delete_test_case"
   #Para cuando vayamos a recalificar
   #put 'submission/update/:id', to: 'submission#update', as: "submission_update"

  get 'user/paginate', to: 'user#paginate', as: "user_paginate"
  get 'submission/paginate', to: 'submission#paginate', as: "submission_paginate"
  get 'contest/paginate', to: 'contest#paginate', as: "contest_paginate"
  get 'submission/:submission_id/', to: 'submission#show_details_submission', as: "submission_show"


  get 'problem/:problem_id/testcase/:test_idx', to: 'test_case#show_test_case', as: "problem_show_test_case"
  put 'problem/:problem_id/testcase/update/:test_idx', to: 'test_case#edit', as: "problem_edit_test_case"
  post 'problem/rejudge/:id', to:'problem#rejudge', as: 'problem_rejudge'
  

  get 'contest/index', to: 'contest#index', as: "contest_index"
  get 'contest/new', to: 'contest#new', as: "contest_new"
  get 'contest/my_contests', to: 'contest#my_contests', as: "my_contests"
  get 'contest/:id', to:'contest#show', as: "contest"
  post 'contest', to: 'contest#create', as:'contests'
  get 'contest/edit/:id', to: 'contest#edit', as: "contest_edit"
  patch 'contest/:id', to: 'contest#update', as: "contest_update"
  post 'contest/:contest_id/problem/:problem_id', to: 'contest#add_problem', as: 'contest_add_problem'
  delete 'contest/:contest_id/problem/:problem_index', to: 'contest#delete_problem', as: 'contest_delete_problem'
  put 'contest/:contest_id/problem/:problem_index', to: 'contest#update_problem', as: 'contest_update_problem'
  post 'contest/:contest_id/register/:user_id', to: 'contest#register', as: 'contest_register'
  post 'contest/:contest_id/register/', to: 'contest#register_group', as: 'contest_register_group'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)
    if Teacher.where(username: user.username).count > 0 
      can :manage, :all
    else
      can :read, [Contest, Problem]
      can :manage, Submission
      can :register, Contest
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contest.rb
class Contest < ApplicationRecord
	belongs_to :teacher
	
	attr_accessor :contest_running

	validates :name, :start_date, :end_date, presence: { message: "es obligatorio" }
	validate :dates_are_correct
	validate :valid_initial_date, unless: :contest_running

	has_many :problem_contest_relationships, dependent: :destroy
	has_many :problems, through: :problem_contest_relationships

	has_many :user_contest_relationships, dependent: :destroy
	has_many :users, through: :user_contest_relationships

	def dates_are_correct
		# Esto es para evita que una persona temine un contest en tiempo anterior al actual
		# pero posterior al start_date
		cur_time = Time.new + 5*60
	    if start_date < end_date == false
	      errors.add(:start_date, 'debe ser antes de la fecha final')
	    elsif cur_time < end_date == false
	      errors.add(:end_date, 'El contest no puede terminar tan pronto')
	    end
  	end

  	def valid_initial_date
		#Esto es para que el contest empiece minimo 5 minutos despues de la fecha actual
		cur_time = Time.new + 5*60
	    if cur_time < start_date == false 
	      errors.add(:start_date, 'debe ser al menos 5 minutos despues de la fecha actual')
	    end

  	end

end

app/models/group.rb
class Group < ApplicationRecord
	belongs_to :teacher
	has_many :has_groups, dependent: :destroy
	has_many :students, through: :has_groups
	validates :name, presence: { message: "is required" }

end

app/models/group_and_contest.rb
class GroupAndContest < ApplicationRecord
end

app/models/has_group.rb
class HasGroup < ApplicationRecord
  belongs_to :student
  belongs_to :group
  validate :student_unique_per_group

  private
  def student_unique_per_group
  	if self.class.exists?(:student_id => student_id, :group_id => group_id)
	  errors.add :student_id, 'Ya se encuentra en el grupo'
	end
  end
end

app/models/problem.rb
class Problem < ApplicationRecord
	mount_uploader :url_statement, FileUploader
	validates_processing_of :url_statement
	validates :name, :time_limit, presence: { message: "no puede estar vacio" }
	validates :time_limit, numericality: { message: "debe ser un numero" }
	validates :languages, numericality: { greater_than: 0, message: "debe estar disponible en al menos un lenguaje" }
	has_many :test_cases
    has_many :submissions
    
    has_many :problem_contest_relationships, dependent: :destroy
	has_many :contests, through: :problem_contest_relationships
end

app/models/student.rb
class Student < ApplicationRecord
	
	has_many :has_groups, dependent: :destroy
	has_many :groups, through: :has_groups
	validates :username, presence: true, uniqueness: true
	#validates :cod	, numericality: { only_integer: true, greater_than: 0 }
	#validates :semester, numericality: { only_integer: true, greater_than: 0 }
end

app/models/submission.rb
class Submission < ApplicationRecord
	belongs_to :user
   	belongs_to :problem
   	mount_uploader :url_code, CodeUploader   
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	has_many :groups, dependent: :destroy
	
	validates :username, uniqueness: true, presence: true
end

app/models/test_case.rb
class TestCase < ApplicationRecord
	mount_uploader :url_input, FileUploader
	mount_uploader :url_output, FileUploader
	belongs_to :problem
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  # Include for autentication only with unal emails
  # validates :email, format: { with: /\A[^@\s]+@(unal.edu.co)\z/ }
  validates :username, uniqueness: true, format: { with: /\A[a-zA-Z0-9_]+\z/, message: "only allows alphanumeric and underscore characters" }, length: {minimum: 5, maximum: 15, message: "length must be between 5 and 15 "}
  validates :full_name, presence: true
  has_many :submissions

  has_many :user_contest_relationships, dependent: :destroy
  has_many :contests, through: :user_contest_relationships
end

app/helpers/contest_helper.rb
module ContestHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/problem_helper.rb
module ProblemHelper
end

app/helpers/submission_helper.rb
module SubmissionHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/test_case_helper.rb
module TestCaseHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<%
    Struct.new("Error", :error_class, :error_message)

    def check_error(errors, param)
        if errors.include?(param)
            return Struct::Error.new(" has-error", "*"+errors.full_messages_for(param)[0])
        else 
            return Struct::Error.new( "", "" )
        end
    end
%>
<!DOCTYPE html>
<html>
    
  <head>
    <title>f(UN)Code</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'http://code.jquery.com/jquery-3.1.0.min.js' %>
    <%= javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js' %>
    <%= javascript_include_tag 'https://www.gstatic.com/charts/loader.js' %>
  </head>
  <body>    
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <ul class="navbar-brand"> <%=link_to( image_tag("funcode.png", :alt => "Logo", class: "UNLogo"), pages_index_path )%> </ul>
            </div>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <%= form_tag search_path, method: 'get' do %>
                            <div class="input-group custom-search-form">
                                <%= text_field_tag :search, params[:search], placeholder: 'Buscar...', class: 'form-control' %>
                                <span class="input-group-btn">
                                <%= button_tag(type: "submit", class: "btn btn-default") do %>
                                    <i class="fa fa-search"></i>
                                <% end %>
                                </button>
                            </span>
                            </div>
                            <% end %>
                            <!-- /input-group -->
                        </li>
                        <% if user_signed_in? %>
                            <li>
                                <%= link_to ('/profile/'+current_user.username ) do %>
                                    <i class="fa fa-user fa-fw"></i> Mi perfil
                                <% end %>
                            </li>
                            <li>
                                <%= link_to ( submissions_user_path(current_user.username) ) do %>
                                    <i class="fa fa-upload fa-fw"></i> Mis envios
                                <% end %>
                            </li>
                        <% end %>
                        <li>
                            <a href="#"><i class="fa fa-table fa-fw"></i> Competencias<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <% if user_signed_in? and can? :create, @contest %>
                                    <li>
                                        <%= link_to " Crear competencia ", contest_new_path %>
                                    </li>
                                    <li>
                                        <%= link_to " Mis competencias ", my_contests_path %>
                                    </li>
                                <% end %>
                                <li>
                                    <%= link_to " Todas las competencias ", contest_index_path %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-product-hunt fa-fw"></i> Problemas<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <% if user_signed_in? and can? :create, @problem %>
                                    <li>
                                    <%= link_to "Crear Problema", problem_new_path %>
                                    </li>
                                <% end %>
                                <li>
                                    <%= link_to "Listado de problemas", problem_index_path %>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <% if user_signed_in? and can? :create, @group %>
                            <li>
                                <%= link_to ( teacher_groups_show_path ) do %>
                                    <i class="fa fa-heart fa-fw"></i> Grupos
                                <% end %>
                            </li>
                        <% end %>
                        <% if user_signed_in? %>
                            <li> 
                                <%= link_to destroy_user_session_path, :method => :delete do %>
                                    <i class = "fa fa-sign-out fa-fw"></i> Cerrar sesión
                                <% end %>
                            </li>
                        <% else %>
                            <li> 
                                <%= link_to (new_user_session_path ) do  %>
                                    <i class="fa fa-sign-in fa-fw"></i> Iniciar sesión
                                <% end %>
                            </li>
                            <li class="divider"></li>
                            <li> 
                                <%= link_to (new_user_registration_path ) do  %>
                                    <i class="fa fa-hand-paper-o fa-fw"></i> Crear cuenta
                                <% end %>
                            </li>
                        <% end %>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                <% if notice %>
                    <p class="alert alert-success"><%= notice %></p>
                <% end %>
                <% if alert %>
                    <p class="alert alert-danger"><%= alert %></p>
                <% end %>
                    <%= yield %>
                </div>
            </div>
        </div>
        <!-- /#page-wrapper -->

    </div>
    
  </body>
</html>

app/views/layouts/light_view.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>f(UN)Code</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script>hljs.initHighlightingOnLoad();</script>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<br>
<div class="text-center">
	<%=image_tag("poster.jpg", class: "img-responsive" )%>
</div>

app/views/pages/new_teacher.html.erb
<%= form_tag create_teacher_path, method: 'post' do %>
	<%= label_tag 'Usuario' %>
	<%= text_field_tag :username %>
	<%= submit_tag 'Agregar profesor'%>
<% end %>

app/views/pages/ok.html.erb
<%= current_user.email %>

app/views/pages/profile.html.erb
<%= javascript_include_tag('submission-pie.js') %>
<script type="text/javascript">
	
	google.charts.load("current", {packages:["corechart"]});
	if( <%=@submission_data.size()%> > 1 )
		google.charts.setOnLoadCallback(drawChart);
	function drawChart() {
		var data = google.visualization.arrayToDataTable( <%= @submission_data.inspect.html_safe %> );
		var colors = { 'Accepted': '#54CA36',
					   'Wrong Answer': '#D1361B',
					   'Time Limit Exceeded': '#DED020',
					   'Runtime Error': '#F0A626',
					   'Compilation Error': '#5B5BE7' };
			var slices_colors = {};
			var i = 0;
			<%@submission_data.from(1).each do |ver,cnt|%> 
				slices_colors[i++] = { color: colors[ '<%=ver%>' ] };
			<%end%>

		var options = {
			is3D: true,
			slices: slices_colors,
			chartArea:{ width:'100%', height:'100%'}
	};

	var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
		chart.draw(data, options);
	}

	$(window).resize(function(){
		if( <%=@submission_data.size()%> > 1 ) drawChart();
	});

</script>

<h1>Perfil de <%= @user.full_name %></h1>
<br>

<div class="row">
	<div class="col-lg-5">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-address-book fa-lg" aria-hidden="true"></i> Datos de usuario
			</div>
			<div class="panel-body">
				<ul>
	                <li>Nombre: <%= @user.full_name %></li>
					<li>Username: <%= @user.username %></li>
					<li>Correo: <%= @user.email %></li>
				</ul>
			</div>
		</div>

		<% if @student != nil %>
			<% groups_cnt = @student.groups.count %>
			<div class="panel panel-default">
				<div class="panel-heading">
					<i class="fa fa-users fa-lg" aria-hidden="true"></i> Grupos
					<div class="pull-right">
						<span class="badge"><%=groups_cnt%></span>
					</div>
				</div>
				<div class="panel-body">
					<%if groups_cnt == 0%>
						<span class="text-muted small">
							<em>El usuario no se encuentra inscrito en ningún grupo.</em>
                        </span>
					<%else%>
						<ul>
						<% @student.groups.each do |group| %>
							<li><%= group.name %></li>
						<% end %> 
						</ul>
					<%end%>
				</div>
			</div>
		<% end %>
	</div>
	<div class="col-lg-7">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-pie-chart fa-lg" aria-hidden="true"></i> Porcentajes de veredictos
			</div>
			<div class="panel-body">
				<% if @submission_data.size() == 1 %>
					<span class="text-muted small">
							<em>El usuario no tiene ningún envío calificado.</em>
                    </span>
				<% end %>
				<div id="piechart_3d" ></div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="fa fa-check fa-lg" aria-hidden="true"></i> Problemas aceptados
			</div>
			<div class="panel-body">
				<%if @problems.length == 0%>
					<span class="text-muted small">
							<em>El usuario no tiene ningún problema aceptado.</em>
                    </span>
				<%else%>
					<%@problems.each do |problem|%>
					<div class="col-lg-2">
						<div class="panel panel-success small" style="width: 100px;">
							<div class="panel-heading text-center fixed-panel">
								<%= link_to problem.id, problem_path(problem.id) %>
							</div>
							<div class="panel-body small text-center fixed-panel">
								<%= problem.name %>
							</div>
						</div>
					</div>
					<%end%>
				<%end%>
			</div>
		</div>
	</div>
</div>

app/views/pages/search.html.erb
<div id="users_table" >
	<%= render "/user/table" %>
</div>

<br>

<div id="problems_table" >
	<%= render "/problem/table" %>
</div>

app/views/pages/wrong.html.erb
Algo salio mal.
Imagine el dinosaurio de google...